const messageUtil = {
  OK: "OK",
  EMPTY_FIELD: "Please Enter",
  ALL_READY_EXIST: "Record Already Exist",
  USER_CREATED: "User Created Successfully",
  CLUB_CREATED: "Club Created Successfully",
  RECORD_NOT_CREATED: "Record Not Created",
  NOT_FOUND: "Record Not Found",
  EMAIL_SENT: "Email Sent Successfully",
  CLUB_OWNER_NOT_FOUND: "Club Owner Not Found",
  CLUB_NOT_FOUND: "Club Not Found",
  INCORRECT_PASSWORD: "Incorrect Password",
  LOGIN_SUCCESS: "Login Successfully",
  UNAUTHORIZED: "User not authorized",
  REQUIRED_USER_ID: "User ID is required",
  UPDATE: "Data is successfully updated",
  FILENOTUPLOADED: "File Not Uploaded",
  NAME_STRING_BASE: " Name should be a type of 'text'",
  NAME_STRING_EMPTY: " Name cannot be an empty field",
  NAME_REQUIRED: "Name is required",
  LASTNAME_STRING_BASE: "Last name should be a type of 'text'",
  LASTNAME_STRING_EMPTY: "Last Name cannot be an empty field",
  LASTNAME_REQUIRED: "Last Name is required",
  ROLE_STRING_BASE: "Role should be a type of 'text'",
  ROLE_STRING_EMPTY: "Role cannot be an empty field",
  ROLE_REQUIRED: "Role is required",
  CITY_STRING_BASE: "City should be a type of 'text'",
  CITY_STRING_EMPTY: "City cannot be an empty field",
  CITY_REQUIRED: "City is required",
  EMAIL_STRING_BASE: "Email should be a type of 'text'",
  EMAIL_STRING_EMPTY: "Email cannot be an empty field",
  EMAIL_REQUIRED: "Email is required",
  EMAIL_NOT_VALID: "Email is not valid",
  PASSWORD_STRING_BASE: "Password should be a type of 'text'",
  PASSWORD_STRING_EMPTY: "Password cannot be an empty field",
  PASSWORD_REQUIRED: "Password is required",
  REGISTER_AGAIN: "User not found please register",
  REQUIRED_ALL_FIELD: "Please required all field",
  PASSWORD_NOT_MATCH: "Current password does not match",
  TYPE_INVALID: "Invalid type",
  STATUS_INVALID: "Invalid status value",

  // Product messages
  PRODUCT_TITLE_STRING_BASE: "Product should be a type of text",
  PRODUCT_TITLE_STRING_EMPTY: "Product cannot be an empty field",
  PRODUCT_TITLE_REQUIRED: "Product title is required",
  PRODUCT_DESC_STRING_BASE: "Description should be a type of text",
  PRODUCT_DESC_STRING_EMPTY: "Description cannot be an empty field",
  PRODUCT_DESC_REQUIRED: "Description is required",
  PRODUCT_PRICE_NUMBER_BASE: "Price should be a type of Numbers",
  PRODUCT_PRICE_POSITIVE: "Price cannot be an negitave value",
  PRODUCT_PRICE_REQUIRED: "Price is required",
  PRODUCT_STOCK_NUMBER_BASE: "Stock should be a type of Numbers",
  PRODUCT_STOCK_INTEGER: "Stock cannot be an string ",
  PRODUCT_STOCK_MIN: "Stock minimum is 0",
  PRODUCT_STOCK_REQUIRED: "Stock are required",
  PRODUCT_BRAND_STRING_BASE: "Brand should be a type of text",
  PRODUCT_BRAND_STRING_EMPTY: "Brand cannot be an empty field",
  PRODUCT_BRAND_REQUIRED: "Brand is required",
  PRODUCT_RATING_NUMBER_BASE: "Rating should be a type of Numbers",
  PRODUCT_RATING_MIN: "Minimum rating is 3",
  PRODUCT_RATING_MAX: "Rating is required",
  STOCK: "Stock Available",
  STOCK_OUT: "Out of Stock",
  OVER_STOCK: "Over the Stock",
  INVENTORY_UPDATE: "Inventory Updated Successfully",
  INVENTORY_NOT_FOUND: "please enter inventory first",

  // payment messages
  USER_STRING_BASE: "User should be a type of text",
  USER_STRING_EMPTY: "User cannot be an empty field",
  USER_REQUIRED: "User is required",
  AMOUNT_NUMBER_BASE: "Amount should be a type of Numbers",
  AMOUNT_NUMBER_EMPTY: "Amount cannot be an empty field",
  AMOUNT_REQUIRED: "Amount is required",
  AMOUNT_POSITIVE: "Amount required in postitive",
  CURRENCY_STRING_BASE: "Currency should be a type of text",
  CURRENCY_STRING_EMPTY: "Currency cannot be an empty field",
  CURRENCY_REQUIRED: "Currency is required",
  TYPE_STRING_BASE: "Type should be a type of text",
  TYPE_STRING_EMPTY: "Type cannot be an empty field",
  TYPE_REQUIRED: "Type is required",
  TRANSACTION_STRING_BASE: "Transaction method should be a type of text",
  TRANSACTION_STRING_EMPTY: "Transaction method cannot be an empty field",
  TRANSACTION_REQUIRED: "Transaction method is required",
};
export default messageUtil;
