import express from "express";
const routes = express.Router();
import saleRouter from "./saleRouter.js";
import userRouter from "./userRouter.js";
import alertRouter from "./alertRouter.js";
import forcastRouter from "./forcastRouter.js";
import productRouter from "./productRouter.js";
import paymentRouter from "./paymentRouter.js";
import inventoryRouter from "./inventoryRouter.js";
import notificationRouter from "./notificationRouter.js";
routes.use("/auth", userRouter);
routes.use("/sale", saleRouter);
routes.use("/alert", alertRouter);
routes.use("/forcast", forcastRouter);
routes.use("/product", productRouter);
routes.use("/payment", paymentRouter);
routes.use("/inventory", inventoryRouter);
routes.use("/notification", notificationRouter);
export default routes;
