import express from "express";
const routes = express.Router();
import userRouter from "./userRouter.js";
import alertRouter from "./alertRouter.js";
import productRouter from "./productRouter.js";
import paymentRouter from "./paymentRouter.js";
import inventoryRouter from "./inventoryRouter.js";
import saleRouter from "./saleRouter.js";
import categoryRouter from "./categoryRouter.js";
import notificationRouter from "./notificationRouter.js";
routes.use("/auth", userRouter);
routes.use("/alert", alertRouter);
routes.use("/product", productRouter);
routes.use("/payment", paymentRouter);
routes.use("/inventory", inventoryRouter);
routes.use("/sale", saleRouter);
routes.use("/category", categoryRouter);
routes.use("/notification", notificationRouter);
export default routes;
